#! /bin/sh


# Python autotools wrapper as suggested by
# http://blog.couchbase.com/installing-python-scripts-automake

if test -z "${PYTHONPATH}"; then
   PYTHONPATH=/usr/local/lib/python2.7/dist-packages/dotm
else
   PYTHONPATH=/usr/local/lib/python2.7/dist-packages/dotm:${PYTHONPATH}
fi
export PYTHONPATH
exec python /usr/local/lib/python2.7/dist-packages/dotm/`basename $0`.py "$@"
